name: typology-experiments
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - flake8
  - pyproj<3
  - geopandas<0.9
  - psycopg2
  - geoalchemy2
  - ipython
  - xlrd
  - xlsxwriter
  - jupyterlab
  - python-dotenv
  - black
  - pip
  - pip:
      - --editable .