name: typology-experiments
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - flake8
  - pyproj
  - geopandas
  - psycopg2
  - geoalchemy2
  - ipython
  - xlrd
  - xlsxwriter
  - jupyterlab
  - python-dotenv
  - black
  - pip
  - pip:
      - --editable .
#NOTE: RIGHT AFTER CREATING THE typology-experiments VIRTUAL ENVIRONMENT USING THIS .yml FILE, RUN THESE 5 COMMANDS IN ORDER IN THE TERMINAL: "conda activate typology-experiments", "conda remove --force pyproj", 'python -m pip install "pyproj"', 'python -m pip install "pdfplumber"', AND 'python -m pip install "gspread"'. THOSE FIRST 3 COMMANDS FIX AN ERROR THAT COMES UP LATER WITH geopandas, AND THOSE LAST 2 COMMANDS INSTALL 2 OTHER PACKAGES ARE OTHER PACKAGES I'LL NEED SEPARATE FROM geopandas. FOUND OUT HOW TO FIX THAT ERROR THAT CAME UP WHEN USING geopandas FROM https://stackoverflow.com/a/69642315 (IN TURN FOUND ON https://stackoverflow.com/questions/69630630/on-fresh-conda-installation-of-pyproj-pyproj-unable-to-set-database-path-pypr ), AND FOUND OUT HOW TO COMMENT A LINE IN A .yml FILE FROM https://blog.wplauncher.com/add-comments-to-yaml-file/#:~:text=In%20order%20to%20add%20comments,line%20in%20a%20YAML%20file.